### ISSUE TITLE
خطأ مطبعي

### ISSUE THREAD

**Issue by y5o5** [0xfff0800/info-instagram#1]
شغل جبار نشكرك عليه 
في ملاحظة ما ادري اذا الخطأ من عندي  او خطأ مطبعي 
في خطوات التثبيت الخطوة رقم 4
installr في كلمة 
كتبتها زي ماهي ما تعرف البايثون على الامر 
شلت الار وظبط

**Comment by 0xfff0800** [comment]
يعطيك العافيه راح اتاكد من الخطاء
